server:
  port: 8080
spring:
  application:
    name: orchestrator
  kafka:
    consumer:
      group-id: orchestrator
  data:
    redis:
      database: 0
      host: redis
      port: 6379
      password: 1234
